name: Construir APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Actualizado a v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@master
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Actualizado a v4
        with:
          name: package
          path: bin/*.apk
